// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ShopNest.Core.Entities;

public partial class Payment
{
    public int PaymentId { get; set; }

    public int? OrderId { get; set; }

    public string TransactionId { get; set; }

    public string Status { get; set; }

    public string Method { get; set; }

    public DateTime? PaidAt { get; set; }

    public virtual Order Order { get; set; }
}