// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ShopNest.Core.Entities;

public partial class ProductImage
{
    public int ProImgId { get; set; }

    public int ProductId { get; set; }

    public string ImageUrl { get; set; }

    public virtual Product Product { get; set; }
}